project:
  type: book

book:
  title: "How To Prove It With Lean"
  author: "Daniel J. Velleman"
  chapters:
    - index.qmd
    - Chap1.qmd
    - Chap2.qmd
    - IntroLean.qmd
    - Chap3.qmd



format:
  html:
    theme: cosmo
    css: HTPIwLstyles.css
    syntax-definitions: [lean.xml,state.xml]
    number-depth: 0
  pdf:
    documentclass: scrreprt
