project:
  type: book
  output-dir: docs

book:
  title: "How To Prove It With Lean"
  author: "Daniel J. Velleman"
  page-footer: "© 2023 Daniel J. Velleman.  Short excerpts from <a href='https://doi.org/10.1017/9781108539890'><i>How To Prove It</i></a>, published by Cambridge University Press, reproduced with permission."
  downloads: pdf
  chapters:
    - index.qmd
    - Chap1.qmd
    - Chap2.qmd
    - IntroLean.qmd
    - Chap3.qmd
    - Chap4.qmd
    - Chap5.qmd

format:
  html:
    theme: cosmo
    css: HTPIwLstyles.css
    syntax-definitions: [lean.xml,state.xml]
    toc-depth: 2
    number-depth: 0
    include-before-body: mathjaxdefs.tex
  pdf:
    documentclass: scrreprt
    toc-depth: 2
    number-depth: 0
    syntax-definitions: [lean.xml,state.xml]
    include-in-header: inpreamble.tex
    include-before-body: thmdefs.tex
    monofont: JuliaMono
    keep-tex: true
    date: "\\footnotesize\\copyright\\ 2023 Daniel J. Velleman. Short excerpts from \\href{https://https://doi.org/10.1017/9781108539890}{\\emph{How To Prove It}}, published by Cambridge University Press, reproduced with permission."

filters:
  - latex-environment
environments: [quote, ind, inpt, outpt, bef, aft, numex, mdsk, thm, nthm, dfn, ndfn, npf, absnobreak]
commands: excl
